format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/atmosphere/restart_dump.astart
  hashes:
    binhash: 4b7ecd838bb9adc12e7a7a6387aa1722
    md5: a00e1a480d725aa78d7b1e018109f8f2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/atmosphere/um.res.yaml
  hashes:
    binhash: 8d6c0ae8af3aafb776a46df7b501caeb
    md5: c3292f96afbec0b0b3fbba0342e4bf08
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/coupler/a2i.nc
  hashes:
    binhash: e1b5b0dd0fa845596930b522e1a01854
    md5: 6f26d259877287fea7f194094de0617a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/coupler/i2a.nc
  hashes:
    binhash: bfa9242c1a454ad1304a35dbb37e4cb8
    md5: b8386c16b96ac8c7a47b615794d745ca
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/coupler/o2i.nc
  hashes:
    binhash: 8cde2f34b5fe8977e183816cdc4a4f0e
    md5: 936316933e8aae8e5e62dd5c73167122
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ice/cice_in.nml
  hashes:
    binhash: 6b4d0b7dd8194971b1bad58fb43e3111
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ice/ice.restart_file
  hashes:
    binhash: 0badffb053e115b725cd411459ec56ae
    md5: 1f829218252ae5454bacb47d44bef82a
work/ice/RESTART/iced.2016-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ice/iced.2016-01-01-00000.nc
  hashes:
    binhash: e292c3f06d3e67d188fc282bd6c76435
    md5: f740ccd0a694fb04911ad6d737768c2a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ice/mice.nc
  hashes:
    binhash: 15980548788c1e6013ee39773bd9665d
    md5: 83227d54f841ff16a02f2f317d2e7e75
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_age.res.nc
  hashes:
    binhash: 1ba566f7ea2d9173057238eabd40fb1f
    md5: 6468a5196c13b5aa20ba5d17e854497c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 243259fb9449ea57922e33faa7d41194
    md5: 591c914ce66761543c46cbf06dac3925
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 64a00c830421389ebd6fe6874e5214a1
    md5: 3ac2aed314ea5ec1dbde2e77d4827783
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_density.res.nc
  hashes:
    binhash: 59c4c93a7de9ce5ed7b73bf167841987
    md5: 75d31703e7078ae8bb649837908b1486
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 70088d2301336cac4f965cbd82eb928c
    md5: 270877c84cf069ed60d405add258a2f8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: db9e808ca66b38a386deaafce2815ffc
    md5: d9f30635fa6191b0470c8c55528d73d6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 99253311efee15b9805b2439ae82497c
    md5: 9d79467ae8ef7e603a2774fe5326aea6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9d79d658d860f8bd27d819422bc2f215
    md5: c4eeebf67ce9fe64763d4b3b2de4e57a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e9d6a73bb9f8c209dbe8a005b682dc97
    md5: 1168485882015447bca984f165f0c6b9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 68d719050aa2b84185c4a049f9a8848a
    md5: 13cedb1ccde6b993fbd12afc326975f1
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_solo.res
  hashes:
    binhash: 1ce9e100b1a1922ccc0aa2911e4ffbf4
    md5: 08db672f76ec7bccc2d2c601437ccf54
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e24d36fdca7d2554b24d751c1c5a011e
    md5: 8a9492091151bed0d95be41982527b64
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c5876e6107aa2906f23c920b32ce4361
    md5: 5c86a4d589176ca39eaaa83fc2ec4e1e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_tracer.res
  hashes:
    binhash: 2a4bc18f2c50140f15ff2f09b631a3a6
    md5: 86cb0a6ab9869703a4188bb1d51571ed
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 277cc7ef666a93002105f793dab01c28
    md5: 3b5a2c6594efacd5bfa49eaabf568305
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cbed072b16a0ab260caaec44631e174b
    md5: aa109fa18db6e4aab89192323905466f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3d35106655d937ed7308ada78f41d185
    md5: 686abb1554d3e567cbdd86f18e2e4b19
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/esm-historical-esm-historical-1.1-r23i1p1f1-61420273/restart165/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 785bc52d5a011043787da4289fcdaee1
    md5: 310d910f73a376e73b376303cd10a820
