format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/atmosphere/restart_dump.astart
  hashes:
    binhash: 2b4dfc4d1077bc43ba9eda42995f15c0
    md5: b5bb1909f0bdefefe1b642cd1e8a98f6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/atmosphere/um.res.yaml
  hashes:
    binhash: ee2c9869621879f37ad9d159e858a26a
    md5: 0aab93eb029e38d6a0652872838ef14a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/coupler/a2i.nc
  hashes:
    binhash: 0a73f3bd97ac2baec7057c86185139d5
    md5: 3245c818363ff9d80ca9b2b23eb57000
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/coupler/i2a.nc
  hashes:
    binhash: 06969c96b2d88789789dcfd03c4ba31e
    md5: d98a3e40b861463723f950a715442cba
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/coupler/o2i.nc
  hashes:
    binhash: 5374c0114e0f006c083c3603ac9d3141
    md5: 1b45d8692c6ff871fac5ddd7e398495a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ice/cice_in.nml
  hashes:
    binhash: eb6b8c5ee1fb34095333fed69a087004
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ice/ice.restart_file
  hashes:
    binhash: 1f20213b5bb26507f036d6e62e1bf8a2
    md5: f2af7cea6b5bcd5e9f0067f4987e3e44
work/ice/RESTART/iced.0152-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ice/iced.0152-01-01-00000.nc
  hashes:
    binhash: 4bbaf0c19452b269d0495b7c1f82ae19
    md5: fd3ce505d677b52ac7e6646420ead62c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ice/mice.nc
  hashes:
    binhash: 43d2a34b19bd3ab483bad2026b17891c
    md5: fbe83e15990374cd3b8c6c3e9e8ecb7c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_age.res.nc
  hashes:
    binhash: f1687c665ea68919d9e95142310d46bb
    md5: 0fd0f843e29af1573851330732290e08
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3e95ce5968e7ffd6c1befdbeeaacf0ed
    md5: 8fc78a0f041b67d015b41d9ef1f74bd6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b7d6617bf68fc27bbde691a744224ab0
    md5: 7ded368f8a80e8309decb710e2f5f243
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_density.res.nc
  hashes:
    binhash: 4d02dcd5c092b6253bc42485fbc04d72
    md5: e05dae567bf6e0644552fcc4dc0b17a2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 45aa9fecf4ba3830bb29a111867c3147
    md5: caddb54798c9bf6bdf54c018e67299a9
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 78e836abf214a45d3ab057c888dc0125
    md5: aece09fa285ab3228d5f43a9fb9c59ee
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_neutral.res.nc
  hashes:
    binhash: aca729d67610965535671a1daa857b49
    md5: e89cd349dfefc3b9be5a573f67a7b587
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b4d2290a4407c741696cc4af504f0d75
    md5: eb6db06af3cb0eadd2f47d2ac818f835
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e92c9f016c0d4753f924fca19a31fbce
    md5: 863f019572c51f410d43e087509c629b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 138c308ed3f57673cd24f9bc407a2420
    md5: 13cedb1ccde6b993fbd12afc326975f1
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_solo.res
  hashes:
    binhash: 525c51af7b9359d4435c91486cd28c9a
    md5: 642119849f0bfea63fab796a030dfd78
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 362d2bdc3cc6d7584621fdf071dcb12a
    md5: 9c79bccf1f79f89ab98560cb32729c5d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 03b0a9b45bea22055fbd305d84ea63c1
    md5: 7c41b4cd258a180b978f7cd8320b0495
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_tracer.res
  hashes:
    binhash: d343eb4d0183fd115f459d882a8b460b
    md5: c7bcb932bde5043d2bf563541b80b286
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dd776e15772db11f881e48d4eb406b10
    md5: c863358aa432ef052d8c1d91b068ce14
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ff0d0565f4ded6a080477e9b2b74e489
    md5: 302b31454976981b9cf40dce87c9c36b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ba685f6154fc76c5fcc288a4795aedf3
    md5: 03ed52028682b8508e7bca126362d96c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Ndep2-PI-CNP-concentrations-Ndep2-PI-CNP-concentrations-e523e199/restart050/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e7da09939c6e8c45286c5cfb1deb5ae1
    md5: b071752cf6c3322cfc2886f56fe4b79c
